### ISSUE TITLE
cannot complete; in None-lexer file

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_intext_complete#11]
new tab, none lexer. text-
```
df sfdfd ddddddddd dddere ddd
```

After "ddd"-caret. I call plugin, word-completions. No result. 
expected result: list if "dddddddd", "dddere".

**Comment by kvichans** [comment]
Повторил.
ToDo

**Comment by kvichans** [comment]
Уточнил. Строка с кареткой пропускается, и это сделано сознательно для значительного облегчения логики плагина.
Отложу

**Comment by Alexey-T** [comment]
@kvichans ?

**Comment by kvichans** [comment]
Ничего не изменилось с 2017 года
