### ISSUE TITLE
Automatic completion doesn't work

### ISSUE THREAD

**Issue by pablorq** [kvichans/cuda_intext_complete#12]
Hi!

I've installed this plugin but it doesn't activate the word suggestion after write 3 chars, as it was expected.

Example:
```
complete
completed
completion
computer
computers

comp_
```

(The `_` char is for represent the actual cursor position.)

Nothing happens.

But if you forces it from Plugins/In-text Completion/Show list of word-like forms, the word suggestion list appears and you can select the word to complete.

Tested on lexer "none" as well in other lexers, with the same behavior. The settings are the default ones.

Any idea how to fix it?

**Comment by Alexey-T** [comment]
Cud's option "autocomplete_autoshow_chars":3
Did you try it?

>Auto-show auto-completion after typing N word-chars (0: disabled)
Option is for lexer-specific configs, not for user.json config.

**Comment by pablorq** [comment]
This is for the In-text Completion plugin, which used to work for any lexer, also without lexer at all (none).

The plugin has an option for "Minimal base length" = 3 for default.

But now it isn't working.

(This week I have had to do a system reinstall, but the last week it was working fine)

**Comment by Alexey-T** [comment]
OK, Intext Complete plugin don't handle Cud's option autocomplete_autoshow_chars. So I don't know how to make it auto show after typing 3 chars. seems it cannot auto-show. plugin works OK if I call it from Plugins menu.
 @kvichans

**Comment by pablorq** [comment]
I understand that Intext Completion works in a different way than the autocomplete plugin, this is why I've open the issue here and not in the main Cudatext project.

As you have tested, the plugin works from Plugins menu, but it should work as you type. If there is any test or debug that I can do, please let me know.

There is something new on Cudatext that could prevent the plugin to show the options list as you type?

As I said, it was working fine just 10 days ago.


Another option could be to improve the included autocomplete plugin to work at user level, on any lexer (included none lexer).

**Comment by Alexey-T** [comment]
I don't understand how it may work 10 days ago :) because its code dont have the "on_complete" method - so plugin cannot react to built-in Cud's autocomplete!

>The plugin has an option for "Minimal base length" = 3 for default.
But now it isn't working.

Maybe it is working- ie it finds words of len 3+ and not words of len=1...2 ?

**Comment by Alexey-T** [comment]
I see that plugin option 'minimal base len (2...5)' works - if it's set to 3, plugin cannot activate after word len=2, and works for word len=3.

**Comment by pablorq** [comment]
Sorry if I mix the things. I don't mean that this plugin react to the Cud's autocomplete.

I said that 10 days ago the plugin works well by its own. Later I talk about improving Cud's autocomplete for any or none lexer, but this is another story...

I've tested all the values from 2 to 5 in the plugin's configuration, but it doesn't work.

Steps to reproduce:
- Create a new file
- Use default plugin configuration
- Copy the following text:

```
complete
completed
completion
computer
computers
```

- Start to write a `compl`.
- Result: no list appear to select the word.
- Test the plugin: go to Plugins/In-text Completion/"Show list of word-like forms" and the list of words is shown.

**Expected behavior:** after the 3rd char, the list of words should appear.

**Comment by pablorq** [comment]
> I see that plugin option 'minimal base len (2...5)' works - if it's set to 3, plugin cannot activate after word len=2, and works for word len=3.

It works for you?

It doesn't work for me... :(

There's any test that I can do about it?

**Comment by pablorq** [comment]
Well, I find another way to have autocomplete on none lexer files:

- Install "Complete from Text" plugin
- Set Cud's option "autocomplete_autoshow_chars":3 for user.json

Now, with the test that I said before in "Steps to reproduce...", it works.

I know that the Cud's option "autocomplete_autoshow_chars" say: "Option is for lexer-specific configs, not for user.json config.". But it works for the user, in any lexer. :slightly_smiling_face: 


I'm going to uninstall the "In-text Completion" plugin. It seems that it doesn't works.


Now I think that I was confused and the one that was working days ago was this workaround. I'm adding this to my "how-to's".

**Comment by Alexey-T** [comment]
>I'm going to uninstall the "In-text Completion" plugin. It seems that it doesn't works.

I also think - 10 days ago you were using 'Complete from text'. So it works again now. (This plg reacts to Cud's autocomplete_autoshow_chars).

**Comment by pablorq** [comment]
Ok. Thank you for the support!

Nice editor, by the way!
