### ISSUE TITLE
Beta 0.9. Two types of completions

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_intext_complete#3]
Переработанная версия.
1) Меню
![itc-menu](https://cloud.githubusercontent.com/assets/7419630/15828251/350074da-2c17-11e6-96b5-acabbbb90e7c.JPG)

2) Конфиг
![itc-cfg](https://cloud.githubusercontent.com/assets/7419630/15828118/bd274b00-2c16-11e6-8046-d3f8cad2d993.JPG)

3) Предлагается пользоваться сразу двумя списками дополнений: **словами** и **выражениями**.
_Слова_ содержат только буквы/цифры и немного других знаков (по умолчанию только `_`).
_Выражения_ могут содержать все спецзнаки или даже любые непробельные символы. Выражения могут оказаться с пробелами внутри, если включена опция "Expands to include both pair-characters", то есть расширять до парной скобки/кавычки.

4) Оба списка можно использовать перебором (команды `Use next/prev...`) или отобразить целиком (команды `Show list...`). Пока каретка или выделение не изменено, можно 
- переключаться между типами списков,
- после перебора отображать список,
- после отображения продолжать перебор.

5) При отображении списки содержать варианты и номера строк.
Список со "словами"
![itc_wdlist](https://cloud.githubusercontent.com/assets/7419630/15828676/ea14387e-2c18-11e6-917e-47405e86fdfe.JPG)
Список с "выражениями", при включенной опции "Расширять".
![itc_exlist](https://cloud.githubusercontent.com/assets/7419630/15828701/ff1b0b58-2c18-11e6-86fb-982989c2857b.JPG)

6) И списки и перебор начинаются либо с первого варианта, либо с ближайшего (сравнение по номерам строк), если включена "Start with variant from nearest line"

**Comment by Alexey-T** [comment]
Мощный получается плагин, только я им не пользуюсь (очень специфично, вот в Субл есть такая вешь Goto Anything, ей МНОГО кто пользуется)
