### ISSUE TITLE
complete wrd

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_intext_complete#5]
"ca|rect" дополняет до "can"-- Но виш такой- заменять по "can" все слово "caret"

**Comment by kvichans** [comment]
ToDo

**Comment by kvichans** [comment]
fix

**Comment by Alexey-T** [comment]
```
    def nav_to_src_same(self):              return RLS._nav_to_src('same', 'move')
    def nav_to_src_next(self):              return RLS._nav_to_src('next', 'stay')
    def nav_to_src_prev(self):              return RLS._nav_to_src('prev', 'stay')
    def nav_to_src_next_act(self):          return RLS._nav_to_src('next', 'move')
    def nav_to_src_prev_act(self):          return RLS._nav_to_src('prev', 'move')
```

встал на "na|v_to_src_prev". Нет всех слов "na..."

**Comment by kvichans** [comment]
Определитесь. Мой ToDo был к вашему пожеланию искать дополнения к _целому_ слову, внутри которого строит каретка. Мне это понравилось - сделал.
А теперь вы что хотите? Такое впечатление, что хотите искать часть слова _слева от каретки_.

**Comment by Alexey-T** [comment]
мое пожеление было "Дополнение к части слова до каретки"

**Comment by Alexey-T** [comment]
(так делают Ide)

**Comment by kvichans** [comment]
Добавлю опцию. Умолчанием будет текущее поведение: целое слово - мне оказалось удобно.

**Comment by kvichans** [comment]
Перечитал ваш первый пост. Да, я не верно его понял. Подумаю.
