### ISSUE TITLE
Rename of opts

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_intext_complete#8]
I found some lines and guess it is IntextComp

  "itc_min_len": 2,
  "itc_sngl": false,
    "itc_near": true,

need ok reading prefix. "intextcomp_"

**Comment by kvichans** [comment]
Todo

**Comment by kvichans** [comment]
Сделал синонимы: `intextcomp_*` и `itc_*`. Если есть оба, то приоритет у `itc_*`

**Comment by Alexey-T** [comment]
Пусть пишется intextcomp.

**Comment by kvichans** [comment]
Ничего  никуда не "пишется"

**Comment by Alexey-T** [comment]
опция пишется в user.json при закрыти длг опций.

**Comment by kvichans** [comment]
Спасибо. Поправлю

**Comment by kvichans** [comment]
fix
