### ISSUE TITLE
Cart pos wrong

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_intext_complete#9]
File

```
dddaa dddddbb dd22
dd|
```

after "dd" complete to "dddaa". Caret dont go to word end after "dddaa".

**Comment by kvichans** [comment]
Каждому удобно по-своему. Это не ошибка, а задуманный результат

**Comment by kvichans** [comment]
Как вы себе представляете, что будет делать пользователь после вставки? Не вижу никакого удобства от "оставить каретку на месте"

**Comment by Alexey-T** [comment]
пока каретка на месте внутри. "dd|daa". Неудобно.

**Comment by kvichans** [comment]
Поясните претензию.

**Comment by Alexey-T** [comment]
обычно автокомплит такой. Каретка идет в конец

**Comment by Alexey-T** [comment]
см примеры в Паскале, по ctrl+space.

**Comment by kvichans** [comment]
Ага, я сегодня _тупой_. Согласен, что каретка должна прыгать в конец.
ToDo

**Comment by Alexey-T** [comment]
(у меня тоже бывает.)
